#!/usr/bin/env python
import os
import sys
import django
from datetime import timedelta
import random

# Configuration de Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'fasoia.settings')
django.setup()

# Maintenant vous pouvez importer les modèles
from myAppli.models import OffreEmploi, Recruteur, SourceScraping
from django.utils import timezone

# Récupérer un recruteur existant (ou None si aucun)
try:
    recruteur = Recruteur.objects.first()
except:
    recruteur = None
    print("⚠️ Aucun recruteur trouvé, les offres seront créées sans recruteur")

# Récupérer un recruteur existant (à adapter)
recruteur = Recruteur.objects.first()

# ===== OFFRE 1-10 : CRÉATIONS MANUELLES (RECRUTEURS CONNECTÉS) =====

offres_manuelles = [
    # 1. Développeur Full Stack Senior
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Développeur Full Stack Senior",
        secteur=OffreEmploi.SECTEUR_IT,
        description="Nous recherchons un développeur Full Stack expérimenté pour piloter nos projets web et encadrer une équipe de 3 développeurs.",
        missions="• Architecture et développement d'applications web\n• Encadrement de l'équipe technique\n• Revue de code et bonnes pratiques\n• Relations avec les clients",
        profil_recherche="• 5+ ans d'expérience en Python/Django\n• Maîtrise de React/Vue.js\n• Expérience en lead technique\n• Anglais professionnel",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.SENIOR,
        annees_experience_min=5,
        annees_experience_max=10,
        niveau_etude_requis="Bac+5 Informatique",
        domaine_etude="Développement web",
        competences_requises=["Python", "Django", "React", "PostgreSQL", "Docker"],
        competences_souhaitees=["AWS", "Kubernetes", "GraphQL"],
        langues_requises=["Français (courant)", "Anglais (technique)"],
        salaire_min=800000,
        salaire_max=1200000,
        salaire_affiche="800 000 - 1 200 000 FCFA",
        date_limite=timezone.now().date() + timedelta(days=30),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
        est_urgente=True,
    ),
    
    # 2. Chef de Projet Marketing Digital
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Chef de Projet Marketing Digital",
        secteur=OffreEmploi.SECTEUR_MARKETING,
        description="Rejoignez notre agence digitale pour piloter des campagnes innovantes pour nos clients.",
        missions="• Élaboration des stratégies digitales\n• Gestion des campagnes SEA/SEO\n• Pilotage des équipes créatives\n• Reporting et analyse de performance",
        profil_recherche="• 4 ans d'expérience en marketing digital\n• Maîtrise de Google Ads et Meta Business\n• Créativité et analyse\n• Gestion de budget",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=4,
        niveau_etude_requis="Bac+5 Marketing/Communication",
        competences_requises=["Google Ads", "Meta Ads", "SEO", "Analytics"],
        competences_souhaitees=["Photoshop", "WordPress"],
        salaire_min=500000,
        salaire_max=750000,
        date_limite=timezone.now().date() + timedelta(days=25),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 3. Ingénieur en Génie Civil
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Ingénieur en Génie Civil - Projets BTP",
        secteur=OffreEmploi.SECTEUR_CONSTRUCTION,
        description="Grande entreprise de BTP recherche un ingénieur pour superviser ses chantiers à Ouagadougou.",
        missions="• Conception et dimensionnement des ouvrages\n• Suivi et contrôle des chantiers\n• Coordination des équipes techniques\n• Respect des normes et délais",
        profil_recherche="• 5 ans d'expérience en BTP\n• Maîtrise d'AutoCAD et Robot\n• Expérience en gestion de projet\n• Mobilité sur chantiers",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.SENIOR,
        annees_experience_min=5,
        niveau_etude_requis="Ingénieur Génie Civil",
        competences_requises=["AutoCAD", "Robot", "Gestion de projet", "Excel"],
        salaire_min=700000,
        salaire_max=950000,
        date_limite=timezone.now().date() + timedelta(days=35),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 4. Responsable Commercial Export
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Responsable Commercial Export",
        secteur=OffreEmploi.SECTEUR_COMMERCE,
        description="Développez les marchés internationaux de notre entreprise agroalimentaire.",
        missions="• Prospection de nouveaux marchés (UEMOA, CEDEAO)\n• Gestion des relations clients export\n• Participation aux salons professionnels\n• Suivi des expéditions",
        profil_recherche="• 5 ans d'expérience en export\n• Anglais courant\n• Connaissance des procédures douanières\n• Mobilité régionale",
        localisation="Bobo-Dioulasso",
        pays="Burkina Faso",
        region="Hauts-Bassins",
        ville="Bobo-Dioulasso",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.SENIOR,
        annees_experience_min=5,
        niveau_etude_requis="Bac+5 Commerce international",
        competences_requises=["Prospection", "Négociation", "Anglais", "Douane"],
        langues_requises=["Français", "Anglais"],
        salaire_min=600000,
        salaire_max=900000,
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
        est_urgente=True,
    ),
    
    # 5. Comptable Fiscaliste
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Comptable Fiscaliste",
        secteur=OffreEmploi.SECTEUR_FINANCE,
        description="Cabinet d'expertise comptable recherche un spécialiste en fiscalité.",
        missions="• Établissement des déclarations fiscales\n• Conseil fiscal aux clients\n• Optimisation fiscale\n• Veille réglementaire",
        profil_recherche="• 3 ans d'expérience en cabinet\n• Maîtrise de la fiscalité OHADA\n• Expertise Excel\n• Rigueur et discrétion",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="Bac+5 Comptabilité/Fiscalité",
        competences_requises=["Fiscalité", "SYSCOHADA", "Excel", "Déclarations"],
        salaire_min=400000,
        salaire_max=550000,
        date_limite=timezone.now().date() + timedelta(days=40),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 6. Infirmier Diplômé d'État
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Infirmier Diplômé d'État",
        secteur=OffreEmploi.SECTEUR_HEALTH,
        description="Clinique privée recherche infirmier(ère) pour son service de soins généraux.",
        missions="• Soins infirmiers aux patients\n• Administration des traitements\n• Surveillance des constantes\n• Accueil et conseil des familles",
        profil_recherche="• IDE avec expérience\n• Sens de l'écoute et empathie\n• Travail en équipe\n• Disponibilité",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        niveau_etude_requis="Diplôme d'État d'Infirmier",
        competences_requises=["Soins infirmiers", "Urgences", "Dossier patient"],
        salaire_min=250000,
        salaire_max=350000,
        date_limite=timezone.now().date() + timedelta(days=15),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 7. Enseignant de Mathématiques
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Enseignant de Mathématiques - Lycée",
        secteur=OffreEmploi.SECTEUR_EDUCATION,
        description="Lycée privé recherche professeur de mathématiques pour classes de seconde et première.",
        missions="• Enseignement des mathématiques\n• Préparation des cours\n• Suivi pédagogique des élèves\n• Participation aux conseils de classe",
        profil_recherche="• 2 ans d'expérience minimum\n• Pédagogie et patience\n• Capacité à motiver les élèves",
        localisation="Bobo-Dioulasso",
        pays="Burkina Faso",
        region="Hauts-Bassins",
        ville="Bobo-Dioulasso",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        niveau_etude_requis="Maîtrise de Mathématiques",
        competences_requises=["Mathématiques", "Pédagogie", "Programmes scolaires"],
        salaire_min=200000,
        salaire_max=300000,
        date_limite=timezone.now().date() + timedelta(days=25),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 8. Chauffeur Livreur
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Chauffeur Livreur",
        secteur=OffreEmploi.SECTEUR_TRANSPORT,
        description="Entreprise de distribution recherche chauffeurs pour livraisons en ville.",
        missions="• Livraison des marchandises\n• Chargement/déchargement\n• Entretien du véhicule\n• Relation client",
        profil_recherche="• Permis B et C valides\n• 3 ans d'expérience\n• Sens de l'orientation\n• Ponctualité",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="CEP/BEPC",
        competences_requises=["Conduite", "Livraison", "Relation client"],
        salaire_min=150000,
        salaire_max=200000,
        date_limite=timezone.now().date() + timedelta(days=10),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
        est_urgente=True,
    ),
    
    # 9. Assistant RH
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Assistant Ressources Humaines",
        secteur=OffreEmploi.SECTEUR_SERVICE,
        description="Soutenez notre équipe RH dans toutes les missions du département.",
        missions="• Gestion administrative du personnel\n• Suivi des absences et congés\n• Participation au recrutement\n• Organisation des formations",
        profil_recherche="• 2 ans d'expérience\n• Connaissance du droit du travail\n• Organisation\n• Discrétion",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        niveau_etude_requis="Bac+3 RH",
        competences_requises=["Administration", "Excel", "Recrutement", "Droit social"],
        salaire_min=250000,
        salaire_max=350000,
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 10. Community Manager
    OffreEmploi(
        recruteur=recruteur,
        source=OffreEmploi.SOURCE_MANUEL,
        titre="Community Manager",
        secteur=OffreEmploi.SECTEUR_MARKETING,
        description="Animez notre communauté sur les réseaux sociaux et créez du contenu engageant.",
        missions="• Gestion des réseaux sociaux (Facebook, Instagram, LinkedIn)\n• Création de contenu visuel\n• Animation de la communauté\n• Analyse des performances",
        profil_recherche="• 2 ans d'expérience\n• Créativité\n• Maîtrise des outils de design\n• Excellente rédaction",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        region="Centre",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        niveau_etude_requis="Bac+3 Communication",
        competences_requises=["Community management", "Canva", "Photoshop", "Rédaction"],
        salaire_min=250000,
        salaire_max=350000,
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
]

# ===== OFFRE 11-20 : OFFRES SCRAPÉES (SOURCES EXTERNES) =====

sources_externes = ["EmploiBurkinA", "LinkedIn Burkina", "JobAfrique", "OptionCarriere"]

offres_scrapees = [
    # 11. Développeur Mobile Flutter
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12345",
        source_id="EXT12345",
        date_scraping=timezone.now() - timedelta(days=2),
        titre="Développeur Mobile Flutter",
        secteur=OffreEmploi.SECTEUR_IT,
        entreprise_nom="Digital Agency BF",
        entreprise_description="Agence digitale innovante",
        description="Développement d'applications mobiles cross-platform avec Flutter.",
        missions="• Développer des apps iOS/Android\n• Collaborer avec l'équipe UI/UX\n• Maintenir et optimiser le code",
        profil_recherche="• 2 ans d'expérience Flutter\n• Connaissance de Dart\n• Sens du design",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDD,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        niveau_etude_requis="Bac+4 Informatique",
        competences_requises=["Flutter", "Dart", "Git", "REST API"],
        salaire_affiche="À discuter",
        date_limite=timezone.now().date() + timedelta(days=25),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
        est_confirmee=False,
    ),
    
    # 12. Commercial Terrain
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12346",
        source_id="EXT12346",
        date_scraping=timezone.now() - timedelta(days=3),
        titre="Commercial Terrain - Télécoms",
        secteur=OffreEmploi.SECTEUR_COMMERCE,
        entreprise_nom="Moov Africa Burkina",
        description="Développement du portefeuille clients dans le secteur des télécoms.",
        missions="• Prospection de nouveaux clients\n• Vente de solutions mobiles\n• Fidélisation",
        profil_recherche="• 2 ans en vente B2B\n• Bon relationnel\n• Permis B",
        localisation="Bobo-Dioulasso",
        pays="Burkina Faso",
        ville="Bobo-Dioulasso",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        competences_requises=["Prospection", "Négociation", "Relation client"],
        salaire_affiche="200 000 + commissions",
        date_limite=timezone.now().date() + timedelta(days=15),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
        est_urgente=True,
    ),
    
    # 13. Ingénieur Réseau
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12347",
        source_id="EXT12347",
        date_scraping=timezone.now() - timedelta(days=1),
        titre="Ingénieur Réseau et Sécurité",
        secteur=OffreEmploi.SECTEUR_IT,
        entreprise_nom="Orange Burkina",
        description="Administration et sécurisation de l'infrastructure réseau.",
        missions="• Configuration équipements Cisco\n• Mise en place VPN/Sécurité\n• Supervision réseau",
        profil_recherche="• 3 ans d'expérience\n• Certifications Cisco\n• Connaissances Linux",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="Bac+5 Réseaux",
        competences_requises=["Cisco", "Sécurité", "VPN", "Linux"],
        salaire_min=600000,
        salaire_max=800000,
        date_limite=timezone.now().date() + timedelta(days=30),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
    
    # 14. Aide Comptable
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12348",
        source_id="EXT12348",
        date_scraping=timezone.now() - timedelta(days=4),
        titre="Aide Comptable",
        secteur=OffreEmploi.SECTEUR_FINANCE,
        entreprise_nom="Cabinet Fiduciaire d'Afrique",
        description="Assistance à l'équipe comptable dans les tâches quotidiennes.",
        missions="• Saisie comptable\n• Classement et archivage\n• Préparation des déclarations",
        profil_recherche="• 1 an d'expérience\n• Formation comptable\n• SYSCOHADA débutant",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDD,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.DEBUTANT,
        annees_experience_min=1,
        niveau_etude_requis="Bac+2 Comptabilité",
        competences_requises=["Saisie", "Excel", "Organisation"],
        salaire_min=150000,
        salaire_max=200000,
        date_limite=timezone.now().date() + timedelta(days=12),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
    
    # 15. Responsable de Magasin
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12349",
        source_id="EXT12349",
        date_scraping=timezone.now() - timedelta(days=2),
        titre="Responsable de Magasin",
        secteur=OffreEmploi.SECTEUR_COMMERCE,
        entreprise_nom="Groupe In&Fi",
        description="Gestion complète d'un magasin de distribution.",
        missions="• Management d'équipe\n• Gestion des stocks\n• Relation clients\n• Atteinte des objectifs",
        profil_recherche="• 3 ans d'expérience similaire\n• Leadership\n• Gestion de stocks",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        competences_requises=["Management", "Gestion stocks", "Relation client"],
        salaire_affiche="300 000 - 400 000 FCFA",
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
    
    # 16. Technicien de Maintenance
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12350",
        source_id="EXT12350",
        date_scraping=timezone.now() - timedelta(days=5),
        titre="Technicien de Maintenance Industrielle",
        secteur=OffreEmploi.SECTEUR_SERVICE,
        entreprise_nom="Brakina",
        description="Maintenance des équipements de production.",
        missions="• Maintenance préventive et corrective\n• Dépannage électromécanique\n• Amélioration continue",
        profil_recherche="• 3 ans d'expérience\n• Électricité industrielle\n• Mécanique",
        localisation="Bobo-Dioulasso",
        pays="Burkina Faso",
        ville="Bobo-Dioulasso",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="BTS Électromécanique",
        competences_requises=["Électricité", "Mécanique", "Soudure"],
        salaire_min=250000,
        salaire_max=350000,
        date_limite=timezone.now().date() + timedelta(days=25),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
    
    # 17. Agent de Saisie
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12351",
        source_id="EXT12351",
        date_scraping=timezone.now() - timedelta(days=1),
        titre="Agent de Saisie",
        secteur=OffreEmploi.SECTEUR_SERVICE,
        entreprise_nom="Projet ENERGIE",
        description="Saisie de données pour un projet international.",
        missions="• Saisie de données\n• Vérification de cohérence\n• Classement",
        profil_recherche="• Rapidité de frappe\n• Maîtrise Excel\n• Rigueur",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDD,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.DEBUTANT,
        annees_experience_min=0,
        niveau_etude_requis="Bac+2",
        competences_requises=["Saisie", "Excel", "Organisation"],
        salaire_min=150000,
        salaire_max=180000,
        date_limite=timezone.now().date() + timedelta(days=8),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
        est_urgente=True,
    ),
    
    # 18. Stage - Assistant Marketing
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12352",
        source_id="EXT12352",
        date_scraping=timezone.now() - timedelta(days=3),
        titre="Stage - Assistant Marketing",
        secteur=OffreEmploi.SECTEUR_MARKETING,
        entreprise_nom="Agence Média Plus",
        description="Stage de fin d'études en marketing digital.",
        missions="• Création de contenu\n• Gestion réseaux sociaux\n• Veille concurrentielle",
        profil_recherche="• Étudiant en marketing\n• Créativité\n• Motivation",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.STAGE,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.SANS_EXPERIENCE,
        annees_experience_min=0,
        niveau_etude_requis="Bac+3 en cours",
        competences_requises=["Rédaction", "Réseaux sociaux", "Pack Office"],
        salaire_min=50000,
        salaire_max=75000,
        date_limite=timezone.now().date() + timedelta(days=15),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
    
    # 19. Consultant Senior en Organisation
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12353",
        source_id="EXT12353",
        date_scraping=timezone.now() - timedelta(days=6),
        titre="Consultant Senior en Organisation",
        secteur=OffreEmploi.SECTEUR_SERVICE,
        entreprise_nom="Cabinet Conseil Africain",
        description="Conseil en organisation et transformation des entreprises.",
        missions="• Diagnostic organisationnel\n• Accompagnement au changement\n• Formation des équipes",
        profil_recherche="• 8 ans d'expérience en conseil\n• Excellente communication\n• Références",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CONSULTANCE,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.EXPERT,
        annees_experience_min=8,
        niveau_etude_requis="Bac+5 + MBA",
        competences_requises=["Conseil", "Organisation", "Management"],
        salaire_affiche="Honoraires à discuter",
        date_limite=timezone.now().date() + timedelta(days=45),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
    
    # 20. Volontaire - Projet Éducation
    OffreEmploi(
        source=OffreEmploi.SOURCE_SCRAPING,
        source_nom=random.choice(sources_externes),
        source_url="https://emploiburkinA.com/offre/12354",
        source_id="EXT12354",
        date_scraping=timezone.now() - timedelta(days=2),
        titre="Volontaire - Projet Éducation",
        secteur=OffreEmploi.SECTEUR_EDUCATION,
        entreprise_nom="ONG Éducation Pour Tous",
        description="Mission de volontariat dans les écoles primaires en zones rurales.",
        missions="• Soutien scolaire\n• Animation d'activités\n• Sensibilisation",
        profil_recherche="• Diplômé en éducation\n• Motivation\n• Adaptation",
        localisation="Koudougou",
        pays="Burkina Faso",
        region="Centre-Ouest",
        ville="Koudougou",
        type_contrat=OffreEmploi.VOLONTARIAT,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.SANS_EXPERIENCE,
        annees_experience_min=0,
        niveau_etude_requis="Bac+2 minimum",
        competences_requises=["Pédagogie", "Animation", "Adaptabilité"],
        salaire_affiche="Indemnités mensuelles",
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.EN_ATTENTE,
        est_active=True,
    ),
]

# ===== OFFRE 21-30 : OFFRES API PARTENAIRES =====

offres_api = [
    # 21. Data Scientist
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Partenaire Emploi",
        source_url="https://api.partenaire.com/offres/9876",
        source_id="API9876",
        titre="Data Scientist",
        secteur=OffreEmploi.SECTEUR_IT,
        entreprise_nom="Startup Innovation BF",
        description="Analyse de données et développement de modèles prédictifs.",
        missions="• Collecte et nettoyage de données\n• Développement de modèles ML\n• Visualisation des résultats",
        profil_recherche="• 3 ans d'expérience\n• Python, Pandas, Scikit-learn\n• Statistiques",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.TOTAL,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="Bac+5 Data Science",
        competences_requises=["Python", "Machine Learning", "SQL", "Statistics"],
        salaire_min=700000,
        salaire_max=1000000,
        date_limite=timezone.now().date() + timedelta(days=30),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 22. Chef de Chantier
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API BTP Emploi",
        source_url="https://api.btp.com/offres/1234",
        source_id="BTP1234",
        titre="Chef de Chantier BTP",
        secteur=OffreEmploi.SECTEUR_CONSTRUCTION,
        entreprise_nom="Entreprise de Construction Moderne",
        description="Supervision de chantiers de construction.",
        missions="• Organisation des équipes\n• Suivi d'avancement\n• Gestion des approvisionnements",
        profil_recherche="• 5 ans d'expérience\n• Lecture de plans\n• Leadership",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.SENIOR,
        annees_experience_min=5,
        niveau_etude_requis="BTS Génie Civil",
        competences_requises=["Lecture plans", "Management", "Gestion chantier"],
        salaire_min=400000,
        salaire_max=600000,
        date_limite=timezone.now().date() + timedelta(days=35),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 23. Contrôleur de Gestion
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Finance Emploi",
        source_url="https://api.finance.com/offres/5678",
        source_id="FIN5678",
        titre="Contrôleur de Gestion",
        secteur=OffreEmploi.SECTEUR_FINANCE,
        entreprise_nom="Groupe Industriel",
        description="Pilotage de la performance financière.",
        missions="• Élaboration des budgets\n• Analyse des écarts\n• Reporting direction",
        profil_recherche="• 4 ans d'expérience\n• Maîtrise des outils de gestion\n• Anglais",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=4,
        niveau_etude_requis="Bac+5 Finance/Comptabilité",
        competences_requises=["Contrôle gestion", "Excel avancé", "SAP"],
        salaire_min=550000,
        salaire_max=750000,
        date_limite=timezone.now().date() + timedelta(days=25),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 24. Gestionnaire de Paie
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API RH Emploi",
        source_url="https://api.rh.com/offres/9012",
        source_id="RH9012",
        titre="Gestionnaire de Paie",
        secteur=OffreEmploi.SECTEUR_FINANCE,
        entreprise_nom="Cabinet RH Pro",
        description="Gestion complète de la paie pour entreprises clientes.",
        missions="• Établissement des bulletins\n• Déclarations sociales\n• Conseil aux clients",
        profil_recherche="• 3 ans d'expérience en cabinet\n• Maîtrise logiciels de paie\n• Rigueur",
        localisation="Bobo-Dioulasso",
        pays="Burkina Faso",
        ville="Bobo-Dioulasso",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="Bac+3 Gestion Paie",
        competences_requises=["Paie", "Logiciel Sage", "Droit social"],
        salaire_min=350000,
        salaire_max=450000,
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 25. Architecte Logiciel
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Tech Emploi",
        source_url="https://api.tech.com/offres/3456",
        source_id="TECH3456",
        titre="Architecte Logiciel",
        secteur=OffreEmploi.SECTEUR_IT,
        entreprise_nom="SSII Burkina",
        description="Conception d'architecture logicielle pour grands projets.",
        missions="• Définition des architectures\n• Choix technologiques\n• Accompagnement des équipes",
        profil_recherche="• 7 ans d'expérience\n• Expertise Java/.NET\n• Architecture microservices",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.PARTIEL,
        niveau_experience=OffreEmploi.EXPERT,
        annees_experience_min=7,
        niveau_etude_requis="Bac+5 Informatique",
        competences_requises=["Architecture", "Java", "Cloud", "Microservices"],
        salaire_min=1000000,
        salaire_max=1500000,
        date_limite=timezone.now().date() + timedelta(days=40),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
        est_urgente=True,
    ),
    
    # 26. Coordinateur de Projet Humanitaire
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API ONG Emploi",
        source_url="https://api.ong.com/offres/7890",
        source_id="ONG7890",
        titre="Coordinateur de Projet Humanitaire",
        secteur=OffreEmploi.SECTEUR_SERVICE,
        entreprise_nom="ONG Action Humanitaire",
        description="Coordination de projets humanitaires dans le Sahel.",
        missions="• Planification des activités\n• Gestion d'équipe\n• Reporting bailleurs",
        profil_recherche="• 5 ans d'expérience terrain\n• Gestion de cycle de projet\n• Anglais",
        localisation="Dori",
        pays="Burkina Faso",
        region="Sahel",
        ville="Dori",
        type_contrat=OffreEmploi.CDD,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.SENIOR,
        annees_experience_min=5,
        niveau_etude_requis="Bac+5 Gestion de projets",
        competences_requises=["Gestion projet", "Coordination", "Reporting", "Anglais"],
        langues_requises=["Français", "Anglais"],
        salaire_affiche="Selon expérience",
        date_limite=timezone.now().date() + timedelta(days=25),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 27. Pharmacien Responsable
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Santé Emploi",
        source_url="https://api.sante.com/offres/2345",
        source_id="SANTE2345",
        titre="Pharmacien Responsable",
        secteur=OffreEmploi.SECTEUR_HEALTH,
        entreprise_nom="Pharmacie Moderne",
        description="Gestion d'une pharmacie de référence.",
        missions="• Délivrance des médicaments\n• Management d'équipe\n• Gestion des stocks",
        profil_recherche="• Diplômé en pharmacie\n• 3 ans d'expérience\n• Leadership",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="Doctorat en Pharmacie",
        competences_requises=["Pharmacie", "Management", "Gestion stocks"],
        salaire_min=500000,
        salaire_max=700000,
        date_limite=timezone.now().date() + timedelta(days=30),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 28. Agent de Crédit
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Banque Emploi",
        source_url="https://api.banque.com/offres/6789",
        source_id="BANQUE6789",
        titre="Agent de Crédit",
        secteur=OffreEmploi.SECTEUR_FINANCE,
        entreprise_nom="Institution de Microfinance",
        description="Analyse et octroi de crédits aux clients.",
        missions="• Étude des dossiers\n• Analyse financière\n• Suivi des remboursements",
        profil_recherche="• 2 ans d'expérience\n• Connaissance du secteur\n• Rigueur",
        localisation="Ouahigouya",
        pays="Burkina Faso",
        region="Nord",
        ville="Ouahigouya",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=2,
        niveau_etude_requis="Bac+3 Finance/Banque",
        competences_requises=["Analyse crédit", "Relation client", "Excel"],
        salaire_min=250000,
        salaire_max=350000,
        date_limite=timezone.now().date() + timedelta(days=20),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 29. Web Designer
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Créatif Emploi",
        source_url="https://api.creatif.com/offres/1239",
        source_id="CREA1239",
        titre="Web Designer UI/UX",
        secteur=OffreEmploi.SECTEUR_IT,
        entreprise_nom="Studio Créatif",
        description="Conception d'interfaces web et mobiles.",
        missions="• Création de maquettes\n• Design d'interfaces\n• Prototypage",
        profil_recherche="• 3 ans d'expérience\n• Maîtrise Figma/Adobe XD\n• Portfolio",
        localisation="Ouagadougou",
        pays="Burkina Faso",
        ville="Ouagadougou",
        type_contrat=OffreEmploi.FREELANCE,
        teletravail=OffreEmploi.TOTAL,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=3,
        niveau_etude_requis="Bac+3 Design",
        competences_requises=["Figma", "UI/UX", "Adobe Suite", "HTML/CSS"],
        salaire_affiche="TJ 50 000 - 80 000 FCFA",
        date_limite=timezone.now().date() + timedelta(days=15),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
    
    # 30. Formateur en Informatique
    OffreEmploi(
        source=OffreEmploi.SOURCE_API,
        source_nom="API Formation Emploi",
        source_url="https://api.formation.com/offres/4567",
        source_id="FORM4567",
        titre="Formateur en Informatique",
        secteur=OffreEmploi.SECTEUR_EDUCATION,
        entreprise_nom="Centre de Formation Professionnelle",
        description="Formation aux métiers du développement web.",
        missions="• Animation de formations\n• Conception pédagogique\n• Suivi des apprenants",
        profil_recherche="• 4 ans d'expérience\n• Pédagogie\n• Expertise Python/JavaScript",
        localisation="Bobo-Dioulasso",
        pays="Burkina Faso",
        ville="Bobo-Dioulasso",
        type_contrat=OffreEmploi.CDI,
        teletravail=OffreEmploi.NON,
        niveau_experience=OffreEmploi.CONFIRME,
        annees_experience_min=4,
        niveau_etude_requis="Bac+5 Informatique",
        competences_requises=["Python", "JavaScript", "Pédagogie", "Communication"],
        salaire_min=400000,
        salaire_max=550000,
        date_limite=timezone.now().date() + timedelta(days=35),
        statut=OffreEmploi.PUBLIEE,
        est_active=True,
    ),
]

# ===== SAUVEGARDE DE TOUTES LES OFFRES =====

def creer_toutes_offres():
    """Fonction pour créer toutes les offres"""
    toutes_offres = offres_manuelles + offres_scrapees + offres_api
    
    for offre in toutes_offres:
        try:
            offre.save()
            source_display = offre.get_source_display()
            print(f"✅ Offre créée: {offre.titre} - {source_display}")
        except Exception as e:
            print(f"❌ Erreur pour {offre.titre}: {e}")

# Exécuter la création
if __name__ == "__main__":
    creer_toutes_offres()