# Generated by Django 6.0.2 on 2026-02-24 19:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('objet', models.CharField(max_length=100)),
                ('conditions', models.TextField()),
                ('documentsRequis', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('typeAppel', models.CharField(max_length=100)),
                ('criteresTechniques', models.TextField()),
                ('criteresFinanciers', models.TextField()),
                ('caution', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('typeProfil', models.CharField(max_length=100)),
                ('DateInscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=100)),
                ('niveauEtude', models.CharField(max_length=300)),
                ('anneesExperiences', models.IntegerField()),
                ('competences', models.CharField(max_length=300)),
                ('disponibilite', models.CharField(max_length=100)),
                ('niveauLangues', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarnevasDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('contenuBase', models.TextField(null=True)),
                ('variable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typeDocument', models.CharField(max_length=100)),
                ('dateUpload', models.DateField(auto_now_add=True)),
                ('fileUpload', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDossier', models.CharField(max_length=100)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('typeProfil', models.CharField(max_length=100)),
                ('DateInscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=100)),
                ('raisonSociale', models.CharField(max_length=100)),
                ('domaineActive', models.CharField(max_length=100)),
                ('competencesCles', models.CharField(max_length=300)),
                ('localisation', models.CharField(max_length=100)),
                ('taille', models.IntegerField()),
                ('attribut', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarchePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('autoriteContractant', models.CharField(max_length=100)),
                ('typeMarche', models.CharField(max_length=100)),
                ('montantEstime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('procedure', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre_uemoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_limite', models.DateTimeField()),
                ('download_url', models.URLField(max_length=500)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('traite_par_ia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('typeContrat', models.CharField(max_length=100)),
                ('niveauRequis', models.CharField(max_length=100)),
                ('experienceMinimale', models.IntegerField()),
                ('localisation', models.CharField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('autorisation', models.CharField(max_length=300)),
                ('cycleVie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('typeProfil', models.CharField(max_length=100)),
                ('DateInscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('secteur', models.CharField(max_length=100)),
                ('typeStructure', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeleIA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('frequence', models.CharField(max_length=100)),
                ('actif', models.BooleanField()),
            ],
        ),
    ]
