# Generated by Django 6.0.2 on 2026-03-04 20:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('objet', models.CharField(max_length=100)),
                ('conditions', models.TextField()),
                ('documentsRequis', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ami_uemoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_limite', models.TextField()),
                ('download_url', models.URLField(max_length=500)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('traite_par_ia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('typeAppel', models.CharField(max_length=100)),
                ('criteresTechniques', models.TextField()),
                ('criteresFinanciers', models.TextField()),
                ('caution', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('typeProfil', models.CharField(max_length=100)),
                ('dateInscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='ACTIF', max_length=100)),
                ('date_naissance', models.DateField(blank=True, default=None, null=True)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Particulier',
                'verbose_name_plural': 'Particuliers',
            },
        ),
        migrations.CreateModel(
            name='CarnevasDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('contenuBase', models.TextField(null=True)),
                ('variable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typeDocument', models.CharField(max_length=100)),
                ('dateUpload', models.DateField(auto_now_add=True)),
                ('fileUpload', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDossier', models.CharField(max_length=100)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarchePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('autoriteContractant', models.CharField(max_length=100)),
                ('typeMarche', models.CharField(max_length=100)),
                ('montantEstime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('procedure', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre_uemoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_limite', models.TextField()),
                ('download_url', models.URLField(max_length=500)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('traite_par_ia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateField()),
                ('typeContrat', models.CharField(max_length=100)),
                ('niveauRequis', models.CharField(max_length=100)),
                ('experienceMinimale', models.IntegerField()),
                ('localisation', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('autorisation', models.CharField(max_length=300)),
                ('cycleVie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeleIA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('frequence', models.CharField(max_length=100)),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('particulier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidat', serialize=False, to='myAppli.particulier')),
                ('niveauEtude', models.CharField(default='', max_length=300)),
                ('anneesExperiences', models.IntegerField(default=0)),
                ('competences', models.CharField(default='', help_text='Compétences séparées par des virgules', max_length=300)),
                ('disponibilite', models.CharField(default='', max_length=100)),
                ('niveauLangues', models.CharField(default='', max_length=100)),
                ('secteur_recherche', models.CharField(blank=True, default='', max_length=100)),
                ('type_contrat_recherche', models.CharField(blank=True, default='', help_text='CDI, CDD, Stage, etc.', max_length=50)),
                ('localisation_recherche', models.CharField(blank=True, default='', max_length=100)),
                ('salaire_souhaite', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('mobilite', models.BooleanField(default=False, help_text='Prêt à se déplacer')),
                ('cv', models.FileField(blank=True, default=None, null=True, upload_to='cvs/')),
                ('lettre_motivation', models.FileField(blank=True, default=None, null=True, upload_to='lettres/')),
                ('nb_candidatures_envoyees', models.IntegerField(default=0)),
                ('nb_entretiens_obtenus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('particulier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruteur', serialize=False, to='myAppli.particulier')),
                ('organisation', models.CharField(default='', max_length=100)),
                ('secteur', models.CharField(default='', max_length=100)),
                ('typeStructure', models.CharField(default='', help_text='PME, Grande entreprise, Administration, etc.', max_length=100)),
                ('poste_occupe', models.CharField(default='', max_length=100)),
                ('secteurs_recherches', models.JSONField(blank=True, default=list)),
                ('types_contrats_proposes', models.JSONField(blank=True, default=list)),
                ('nb_offres_publiees', models.IntegerField(default=0)),
                ('nb_candidatures_recues', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recruteur',
                'verbose_name_plural': 'Recruteurs',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('typeProfil', models.CharField(max_length=100)),
                ('dateInscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='ACTIF', max_length=100)),
                ('raisonSociale', models.CharField(max_length=100)),
                ('domaineActive', models.CharField(help_text="Secteur d'activité principal", max_length=100)),
                ('competencesCles', models.CharField(help_text='Compétences séparées par des virgules', max_length=300)),
                ('localisation', models.CharField(help_text='Ville, Pays', max_length=100)),
                ('taille', models.IntegerField(help_text="Nombre d'employés")),
                ('description', models.TextField(blank=True, default='', help_text="Présentation de l'entreprise")),
                ('site_web', models.URLField(blank=True, default='')),
                ('annee_creation', models.IntegerField(blank=True, default=None, null=True)),
                ('chiffre_affaires', models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Chiffre d'affaires annuel en FCFA", max_digits=15, null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Capital social en FCFA', max_digits=15, null=True)),
                ('pays_intervention', models.JSONField(blank=True, default=list, help_text="Liste des pays où l'entreprise peut intervenir")),
                ('rayon_action', models.IntegerField(blank=True, default=None, help_text="Rayon d'action en km autour du siège", null=True)),
                ('annees_experience', models.IntegerField(default=0)),
                ('nb_projets_realises', models.IntegerField(default=0)),
                ('references', models.TextField(blank=True, default='', help_text='Principales références')),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('agrements', models.JSONField(blank=True, default=list)),
                ('mots_cles_index', models.JSONField(blank=True, default=list, help_text='Mots-clés extraits automatiquement pour le matching')),
                ('vecteur_embedding', models.JSONField(blank=True, default=None, help_text='Vecteur sémantique pour la recherche avancée', null=True)),
                ('types_opportunites', models.JSONField(blank=True, default=list, help_text="Types d'opportunités souhaités (AMI, APPEL_OFFRE)")),
                ('montant_min', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant minimum recherché', max_digits=15, null=True)),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant maximum recherché', max_digits=15, null=True)),
                ('nb_recommandations_envoyees', models.IntegerField(default=0)),
                ('nb_candidatures_emises', models.IntegerField(default=0)),
                ('taux_succes', models.FloatField(default=0.0, help_text='Taux de succès aux candidatures')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('profil_complet', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'indexes': [models.Index(fields=['domaineActive'], name='myAppli_ent_domaine_5bbd69_idx'), models.Index(fields=['localisation'], name='myAppli_ent_localis_75a435_idx'), models.Index(fields=['taille'], name='myAppli_ent_taille_362aad_idx')],
            },
        ),
    ]
