# Generated by Django 6.0.2 on 2026-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami_uemoa',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='pdfs/'),
        ),
    ]
