# Generated by Django 6.0.2 on 2026-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre_uemoa',
            name='date_limite',
            field=models.TextField(),
        ),
    ]
