# Generated by Django 6.0.2 on 2026-03-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('TECHNIQUE', 'Dossier Technique'), ('FINANCIER', 'Dossier Financier'), ('ADMINISTRATIF', 'Dossier Administratif'), ('CANDIDATURE', 'Dossier de Candidature')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('fichier_template', models.FileField(upload_to='templates/documents/')),
                ('types_opportunites', models.JSONField(default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunite_type', models.CharField(max_length=50)),
                ('opportunite_id', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('COMPLET', 'Complet'), ('SOUMIS', 'Soumis')], default='EN_PREPARATION', max_length=20)),
                ('date_soumission_prevue', models.DateField()),
                ('date_soumission_effective', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='myAppli.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_document', models.CharField(max_length=255)),
                ('fichier_genere', models.FileField(upload_to='soumissions/documents/')),
                ('taille_fichier', models.IntegerField(default=0)),
                ('donnees_saisies', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('A_REVOIR', 'À réviser')], default='BROUILLON', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myAppli.dossiersoumission')),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myAppli.modeledocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='dossiersoumission',
            index=models.Index(fields=['entreprise', 'statut'], name='myAppli_dos_entrepr_a81d45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dossiersoumission',
            unique_together={('entreprise', 'opportunite_type', 'opportunite_id')},
        ),
    ]
