# Generated by Django 6.0.2 on 2026-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0002_alter_ami_uemoa_fichier_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentgenere',
            options={'ordering': ['type_document']},
        ),
        migrations.AddField(
            model_name='documentgenere',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentgenere',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentgenere',
            name='fichier_source',
            field=models.FileField(blank=True, help_text='Fichier original importé', null=True, upload_to='documents/sources/'),
        ),
        migrations.AlterField(
            model_name='documentgenere',
            name='contenu_html',
            field=models.TextField(blank=True, help_text='Pour les documents textuels modifiables', null=True),
        ),
        migrations.AlterField(
            model_name='documentgenere',
            name='statut',
            field=models.CharField(choices=[('MISSING', 'Manquant'), ('GENERATED', 'Généré'), ('IMPORTED', 'Importé'), ('MODIFIED', 'Modifié'), ('ARCHIVED', 'Archivé')], default='MISSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentgenere',
            name='type_document',
            field=models.CharField(choices=[('ENTETE', 'En-tête'), ('LETTRE', 'Lettre de motivation'), ('PRESENTATION', 'Présentation entreprise'), ('FICHE', 'Fiche de renseignement'), ('MATERIEL', 'Liste matériel'), ('PERSONNEL', 'Liste personnel')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='documentgenere',
            unique_together={('dossier', 'type_document')},
        ),
    ]
