# Generated by Django 6.0.2 on 2026-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0002_alter_offre_uemoa_date_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ami_uemoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_limite', models.TextField()),
                ('download_url', models.URLField(max_length=500)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('traite_par_ia', models.BooleanField(default=False)),
            ],
        ),
    ]
