# Generated by Django 6.0.2 on 2026-03-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0002_modeledocument_dossiersoumission_documentsoumission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami',
            name='dateLimite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ami_uemoa',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='dateLimite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marchepublic',
            name='dateLimite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offre_uemoa',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='dateLimite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
