# Generated by Django 6.0.2 on 2026-02-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0002_citation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='author',
            new_name='date_limite',
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='tags',
            new_name='download_url',
        ),
    ]
