# Generated by Django 6.0.2 on 2026-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0003_ami_uemoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='attribut',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='agrements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='annee_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='annees_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital social en FCFA', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='chiffre_affaires',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Chiffre d'affaires annuel en FCFA", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True, help_text="Présentation de l'entreprise"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='montant_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum recherché', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='montant_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum recherché', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='mots_cles_index',
            field=models.JSONField(blank=True, default=list, help_text='Mots-clés extraits automatiquement pour le matching'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nb_candidatures_emises',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nb_projets_realises',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nb_recommandations_envoyees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='pays_intervention',
            field=models.JSONField(blank=True, default=list, help_text="Liste des pays où l'entreprise peut intervenir"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='profil_complet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='rayon_action',
            field=models.IntegerField(blank=True, help_text="Rayon d'action en km autour du siège", null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='references',
            field=models.TextField(blank=True, help_text='Principales références'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='taux_succes',
            field=models.FloatField(default=0.0, help_text='Taux de succès aux candidatures'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='types_opportunites',
            field=models.JSONField(blank=True, default=list, help_text="Types d'opportunités souhaités (AMI, APPEL_OFFRE)"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='vecteur_embedding',
            field=models.JSONField(blank=True, help_text='Vecteur sémantique pour la recherche avancée', null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(default='ACTIF', max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='competencesCles',
            field=models.CharField(help_text='Compétences séparées par des virgules', max_length=300),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='domaineActive',
            field=models.CharField(help_text="Secteur d'activité principal", max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='localisation',
            field=models.CharField(help_text='Ville, Pays', max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='statut',
            field=models.CharField(default='ACTIF', max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='taille',
            field=models.IntegerField(help_text="Nombre d'employés"),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='statut',
            field=models.CharField(default='ACTIF', max_length=100),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['domaineActive'], name='myAppli_ent_domaine_5bbd69_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['localisation'], name='myAppli_ent_localis_75a435_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['taille'], name='myAppli_ent_taille_362aad_idx'),
        ),
    ]
