# Generated by Django 6.0.2 on 2026-04-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0003_alter_documentgenere_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgenere',
            name='type_document',
            field=models.CharField(choices=[('ENVELOPPE', 'Message enveloppe'), ('LETTRE', 'Lettre de motivation'), ('PRESENTATION', 'Présentation entreprise'), ('FICHE', 'Fiche de renseignement'), ('MATERIEL', 'Liste matériel'), ('PERSONNEL', 'Liste personnel')], max_length=20),
        ),
    ]
