# Generated by Django 6.0.2 on 2026-02-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0003_rename_author_citation_date_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='download_url',
            field=models.URLField(),
        ),
    ]
