# Generated by Django 6.0.2 on 2026-03-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0003_alter_ami_datelimite_alter_ami_uemoa_date_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsoumission',
            name='fichier_genere',
            field=models.FileField(max_length=255, upload_to='soumissions/documents/'),
        ),
    ]
