# Generated by Django 6.0.2 on 2026-03-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0004_alter_entreprise_options_remove_entreprise_attribut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('partenaire', 'Partenaire')], default='particulier', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
