# Generated by Django 6.0.2 on 2026-03-11 20:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0004_alter_documentsoumission_fichier_genere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMI',
        ),
        migrations.DeleteModel(
            name='AppelOffre',
        ),
        migrations.DeleteModel(
            name='CarnevasDocument',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
        migrations.DeleteModel(
            name='MarchePublic',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.DeleteModel(
            name='ServiceIA',
        ),
        migrations.AlterModelOptions(
            name='offreemploi',
            options={'ordering': ['-date_publication'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='dateLimite',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='datePublication',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='experienceMinimale',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='niveauRequis',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='typeContrat',
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='annees_experience_min',
            field=models.IntegerField(default=0, help_text="Années d'expérience minimum requises"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='competences_requises',
            field=models.JSONField(blank=True, default=list, help_text='Liste des compétences requises'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='competences_souhaitees',
            field=models.JSONField(blank=True, default=list, help_text='Liste des compétences souhaitées'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='date_limite',
            field=models.DateField(blank=True, help_text='Date limite de candidature', null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='est_active',
            field=models.BooleanField(default=True, help_text="L'offre est-elle visible ?"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='missions',
            field=models.TextField(blank=True, help_text='Description des missions principales'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='mots_cles_index',
            field=models.JSONField(blank=True, default=list, help_text='Mots-clés pour la recherche'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveau_etude_requis',
            field=models.CharField(blank=True, help_text='Ex: Bac+5, Master, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveau_experience',
            field=models.CharField(choices=[('Débutant', 'Débutant (moins de 2 ans)'), ('Intermédiaire', 'Intermédiaire (2-5 ans)'), ('Confirmé', 'Confirmé (5-10 ans)'), ('Expert', 'Expert (plus de 10 ans)')], default='Débutant', max_length=20),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nombre_candidatures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nombre_vues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_recherche',
            field=models.TextField(blank=True, help_text='Profil idéal du candidat'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_emploi', to='myAppli.recruteur'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_affiche',
            field=models.CharField(blank=True, help_text='Texte libre pour le salaire', max_length=100),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire maximum en FCFA', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire minimum en FCFA', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('POURVOIE', 'Pourvue'), ('FERMEE', 'Fermée'), ('EXPIREE', 'Expirée')], default='BROUILLON', max_length=20),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='teletravail',
            field=models.BooleanField(default=False, help_text='Télétravail possible'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Freelance', 'Freelance'), ('Temps partiel', 'Temps partiel'), ('Saisonnier', 'Saisonnier')], default='CDI', max_length=20),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='localisation',
            field=models.CharField(help_text='Ville, Pays', max_length=200),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['recruteur', 'statut'], name='myAppli_off_recrute_47112d_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['date_limite'], name='myAppli_off_date_li_4bc523_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['type_contrat'], name='myAppli_off_type_co_ffec9e_idx'),
        ),
    ]
