# Generated by Django 6.0.2 on 2026-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0004_alter_documentgenere_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='entete_image',
            field=models.ImageField(blank=True, help_text="Image d'en-tête (contenant logo + infos entreprise)", null=True, upload_to='entetes/'),
        ),
    ]
