# Generated by Django 6.0.2 on 2026-04-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0005_entreprise_entete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='taille',
            field=models.IntegerField(blank=True, default=0, help_text="Nombre d'employés", null=True),
        ),
    ]
