# Generated by Django 6.0.2 on 2026-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0005_delete_ami_delete_appeloffre_delete_carnevasdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_importation',
            field=models.DateTimeField(blank=True, help_text="Date d'importation pour les offres scrapées", null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='source',
            field=models.CharField(choices=[('RECRUTEUR', 'Publiée par un recruteur'), ('SCRAPING', 'Importée automatiquement'), ('ADMIN', "Créée par l'administrateur"), ('API', 'Importée via API')], default='RECRUTEUR', help_text="Origine de l'offre d'emploi", max_length=20),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='source_url',
            field=models.URLField(blank=True, help_text="URL d'origine si l'offre a été importée", max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['source'], name='myAppli_off_source_83cd28_idx'),
        ),
    ]
