# Generated by Django 6.0.2 on 2026-03-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0006_offreemploi_date_importation_offreemploi_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Mon CV', max_length=200)),
                ('style', models.CharField(choices=[('moderne', 'Moderne'), ('classique', 'Classique'), ('minimaliste', 'Minimaliste'), ('professionnel', 'Professionnel'), ('creatif', 'Créatif')], default='moderne', max_length=20)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('permis', models.CharField(blank=True, help_text='Permis de conduire', max_length=100)),
                ('resume', models.TextField(blank=True, help_text='Résumé / Objectif professionnel')),
                ('competences', models.JSONField(blank=True, default=list)),
                ('langues', models.JSONField(blank=True, default=list)),
                ('experiences', models.JSONField(blank=True, default=list)),
                ('formations', models.JSONField(blank=True, default=list)),
                ('centres_interet', models.TextField(blank=True)),
                ('fichier_genere', models.FileField(blank=True, help_text='Fichier PDF du CV généré', null=True, upload_to='cvs/generes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='myAppli.candidat')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
