# Generated by Django 6.0.2 on 2026-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0006_alter_entreprise_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='offres_emploi/'),
        ),
    ]
