# Generated by Django 6.0.2 on 2026-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0007_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateTimeField(blank=True, null=True)),
                ('objet', models.CharField(max_length=100)),
                ('conditions', models.TextField()),
                ('documentsRequis', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateTimeField(blank=True, null=True)),
                ('typeAppel', models.CharField(max_length=100)),
                ('criteresTechniques', models.TextField()),
                ('criteresFinanciers', models.TextField()),
                ('caution', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarnevasDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('contenuBase', models.TextField(null=True)),
                ('variable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typeDocument', models.CharField(max_length=100)),
                ('dateUpload', models.DateField(auto_now_add=True)),
                ('fileUpload', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDossier', models.CharField(max_length=100)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarchePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.CharField(max_length=100)),
                ('datePublication', models.DateField()),
                ('dateLimite', models.DateTimeField(blank=True, null=True)),
                ('autoriteContractant', models.CharField(max_length=100)),
                ('typeMarche', models.CharField(max_length=100)),
                ('montantEstime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('procedure', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('autorisation', models.CharField(max_length=300)),
                ('cycleVie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeleIA', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='candidat',
        ),
        migrations.RemoveIndex(
            model_name='offreemploi',
            name='myAppli_off_recrute_47112d_idx',
        ),
        migrations.RemoveIndex(
            model_name='offreemploi',
            name='myAppli_off_date_li_4bc523_idx',
        ),
        migrations.RemoveIndex(
            model_name='offreemploi',
            name='myAppli_off_type_co_ffec9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='offreemploi',
            name='myAppli_off_source_83cd28_idx',
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.DeleteModel(
            name='OffreEmploi',
        ),
    ]
