# Generated by Django 6.0.2 on 2026-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0007_offreemploi_fichier_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='documents_exiges',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['CV', 'Lettre motivation', 'Diplôme', 'CNI']"),
        ),
    ]
