# Generated by Django 6.0.2 on 2026-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0008_ami_appeloffre_carnevasdocument_document_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami_uemoa',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='offre_uemoa',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='pdfs/'),
        ),
    ]
