# Generated by Django 6.0.2 on 2026-04-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0008_offreemploi_documents_exiges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('SOUMIS', 'Soumis'), ('VU', 'Vu par le recruteur'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_PREPARATION', max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidatures/lettres/')),
                ('lettre_generee', models.TextField(blank=True, help_text='Lettre générée par IA')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='candidatures/autres/')),
                ('score_compatibilite', models.FloatField(default=0.0, help_text='Score de compatibilité CV ↔ Offre')),
                ('analyse_cv', models.TextField(blank=True, help_text="Analyse IA du CV par rapport à l'offre")),
                ('analyse_lettre', models.TextField(blank=True, help_text='Analyse IA de la lettre')),
                ('message_candidat', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_candidature', to='myAppli.candidat')),
                ('cv_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='myAppli.cvgenere')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_candidature', to='myAppli.offreemploi')),
            ],
            options={
                'verbose_name': 'Dossier de candidature',
                'verbose_name_plural': 'Dossiers de candidature',
                'ordering': ['-date_creation'],
                'unique_together': {('candidat', 'offre')},
            },
        ),
        migrations.DeleteModel(
            name='Candidature',
        ),
    ]
