# Generated by Django 6.0.2 on 2026-04-30 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0009_dossiercandidature_delete_candidature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreMotivationGeneree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Lettre pour Développeur Python - Entreprise X', max_length=200)),
                ('contenu', models.TextField(help_text='Contenu de la lettre générée par IA')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='lettres/pdf/')),
                ('fichier_docx', models.FileField(blank=True, null=True, upload_to='lettres/docx/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('est_favori', models.BooleanField(default=False)),
                ('est_utilisee', models.BooleanField(default=False)),
                ('nb_utilisations', models.IntegerField(default=0)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lettres_generees', to='myAppli.candidat')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettres_generees', to='myAppli.offreemploi')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lettres_generees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lettre de motivation générée',
                'verbose_name_plural': 'Lettres de motivation générées',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='lettre_generee_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='myAppli.lettremotivationgeneree'),
        ),
    ]
