# Generated by Django 6.0.2 on 2026-03-16 19:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0009_alter_ami_uemoa_fichier_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami_uemoa',
            name='fichier_local',
            field=models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='pdfs'),
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du poste')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence interne')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('missions', models.TextField(blank=True, verbose_name='Missions principales')),
                ('profil_recherche', models.TextField(blank=True, verbose_name='Profil recherché')),
                ('localisation', models.CharField(max_length=255, verbose_name='Lieu de travail')),
                ('pays', models.CharField(default='Burkina Faso', max_length=100, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('TEMPORAIRE', 'Temporaire')], default='CDI', max_length=20, verbose_name='Type de contrat')),
                ('teletravail', models.CharField(choices=[('NON', 'Non'), ('PARTIEL', 'Partiel'), ('TOTAL', 'Total')], default='NON', max_length=10, verbose_name='Télétravail possible')),
                ('niveau_experience', models.CharField(choices=[('DEBUTANT', 'Débutant (0-2 ans)'), ('CONFIRME', 'Confirmé (3-5 ans)'), ('SENIOR', 'Sénior (6-10 ans)'), ('EXPERT', 'Expert (10+ ans)')], default='DEBUTANT', max_length=20, verbose_name="Niveau d'expérience requis")),
                ('annees_experience_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name="Années d'expérience minimum")),
                ('niveau_etude_requis', models.CharField(blank=True, max_length=100, verbose_name="Niveau d'étude requis")),
                ('competences_requises', models.JSONField(blank=True, default=list, verbose_name='Compétences requises')),
                ('competences_souhaitees', models.JSONField(blank=True, default=list, verbose_name='Compétences souhaitées')),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Salaire minimum (FCFA)')),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Salaire maximum (FCFA)')),
                ('salaire_affiche', models.CharField(blank=True, max_length=100, verbose_name='Salaire (texte libre)')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite de candidature')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début souhaitée')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('POURVOIE', 'Pourvue'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('est_active', models.BooleanField(default=True, verbose_name='Offre active')),
                ('est_urgente', models.BooleanField(default=False, verbose_name='Offre urgente')),
                ('nb_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('nb_candidatures', models.PositiveIntegerField(default=0, verbose_name='Nombre de candidatures')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_emploi', to='myAppli.recruteur', verbose_name='Recruteur')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('cv_envoye', models.FileField(blank=True, null=True, upload_to='candidatures/cv/', verbose_name='CV envoyé')),
                ('lettre_motivation_envoyee', models.FileField(blank=True, null=True, upload_to='candidatures/lettres/', verbose_name='Lettre de motivation envoyée')),
                ('notes_recruteur', models.TextField(blank=True, verbose_name='Notes du recruteur')),
                ('date_entretien', models.DateTimeField(blank=True, null=True, verbose_name="Date d'entretien")),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='myAppli.candidat', verbose_name='Candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='myAppli.offreemploi', verbose_name="Offre d'emploi")),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
            },
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['statut', 'est_active'], name='myAppli_off_statut_452a24_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['date_publication'], name='myAppli_off_date_pu_b1431d_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['recruteur'], name='myAppli_off_recrute_38c486_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('offre', 'candidat')},
        ),
    ]
