# Generated by Django 6.0.2 on 2026-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0010_lettremotivationgeneree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercandidature',
            name='points_faibles',
            field=models.JSONField(blank=True, default=list, help_text="Points faibles identifiés par l'IA"),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='points_forts',
            field=models.JSONField(blank=True, default=list, help_text="Points forts identifiés par l'IA"),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='score_competences',
            field=models.FloatField(default=0.0, help_text='Score de compatibilité sur les compétences'),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='score_experience',
            field=models.FloatField(default=0.0, help_text="Score de compatibilité sur l'expérience"),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='score_formation',
            field=models.FloatField(default=0.0, help_text='Score de compatibilité sur la formation'),
        ),
    ]
