# Generated by Django 6.0.2 on 2026-03-18 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0010_alter_ami_uemoa_fichier_local_offreemploi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom affiché du style', max_length=100)),
                ('categorie', models.CharField(help_text='Identifiant unique du style (moderne, classique, etc.)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du style')),
                ('image_apercu', models.ImageField(blank=True, null=True, upload_to='modeles/apercus/')),
                ('est_populaire', models.BooleanField(default=False)),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'apparition dans le sélecteur")),
                ('nb_utilisations', models.IntegerField(default=0, help_text='Nombre de fois que ce style a été utilisé')),
                ('est_actif', models.BooleanField(default=True, help_text='Visible dans le sélecteur')),
                ('est_premium', models.BooleanField(default=False, help_text='Réservé aux utilisateurs premium')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de CV',
                'verbose_name_plural': 'Modèles de CV',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CVGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('donnees_cv', models.JSONField(default=dict, help_text='Toutes les données du CV au format JSON')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='cvs/pdf/')),
                ('fichier_docx', models.FileField(blank=True, null=True, upload_to='cvs/docx/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('est_public', models.BooleanField(default=False, help_text='Rendre le CV visible pour les recruteurs')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs_generes', to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='myAppli.modelecv')),
            ],
            options={
                'verbose_name': 'CV généré',
                'verbose_name_plural': 'CVs générés',
                'ordering': ['-date_generation'],
            },
        ),
    ]
