# Generated by Django 6.0.2 on 2026-03-19 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0011_modelecv_cvgenere'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('EN_COURS', 'En cours')], max_length=20)),
                ('offres_trouvees', models.IntegerField(default=0)),
                ('offres_nouvelles', models.IntegerField(default=0)),
                ('offres_mises_a_jour', models.IntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Log de scraping',
                'verbose_name_plural': 'Logs de scraping',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SourceScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('url_base', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('API', 'API REST'), ('HTML', 'Site HTML'), ('RSS', 'Flux RSS'), ('JSON', 'Fichier JSON')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('frequence', models.IntegerField(default=24, help_text='Fréquence de scraping en heures')),
                ('dernier_scraping', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict, help_text='Configuration spécifique')),
            ],
            options={
                'verbose_name': 'Source de scraping',
                'verbose_name_plural': 'Sources de scraping',
            },
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='annees_experience_max',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name="Années d'expérience maximum"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='date_scraping',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de scraping'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='domaine_etude',
            field=models.CharField(blank=True, max_length=100, verbose_name="Domaine d'étude"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise_description',
            field=models.TextField(blank=True, verbose_name="Description de l'entreprise"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise_logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise_nom',
            field=models.CharField(blank=True, help_text='Pour les offres sans recruteur associé', max_length=255, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise_site_web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Site web de l'entreprise"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone de contact'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='est_confirmee',
            field=models.BooleanField(default=False, help_text='Pour les offres scrapées, indique si les infos ont été vérifiées', verbose_name='Offre confirmée'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='hash_contenu',
            field=models.CharField(blank=True, help_text='Pour détecter les doublons', max_length=64, null=True, verbose_name='Hash du contenu'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='langues_requises',
            field=models.JSONField(blank=True, default=list, verbose_name='Langues requises'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nb_clics',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de clics'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nb_partages',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de partages'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données originales du scraping', verbose_name='Données brutes'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_devise',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='secteur',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('COMMERCE', 'Commerce / Distribution'), ('CONSTRUCTION', 'Construction / BTP'), ('EDUCATION', 'Éducation / Formation'), ('FINANCE', 'Finance / Comptabilité'), ('HEALTH', 'Santé / Social'), ('IT', 'Informatique / Télécoms'), ('MARKETING', 'Marketing / Communication'), ('SERVICE', 'Services'), ('TRANSPORT', 'Transport / Logistique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='source',
            field=models.CharField(choices=[('MANUEL', 'Création manuelle'), ('SCRAPING', 'Scraping automatique'), ('API', 'API externe'), ('IMPORT', 'Import de fichier'), ('PARTENAIRE', 'Partenaire')], default='MANUEL', max_length=20, verbose_name="Source de l'offre"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='source_id',
            field=models.CharField(blank=True, help_text='Identifiant unique dans le système source', max_length=200, null=True, verbose_name='ID source'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='source_nom',
            field=models.CharField(blank=True, help_text='Ex: EmploiBurkinA, LinkedIn, etc.', max_length=100, null=True, verbose_name='Nom de la source'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='source_url',
            field=models.URLField(blank=True, help_text="URL d'origine si issue de scraping/API", max_length=500, null=True, verbose_name='URL source'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='niveau_experience',
            field=models.CharField(choices=[('SANS_EXP', 'Sans expérience'), ('DEBUTANT', 'Débutant (0-2 ans)'), ('CONFIRME', 'Confirmé (3-5 ans)'), ('SENIOR', 'Sénior (6-10 ans)'), ('EXPERT', 'Expert (10+ ans)')], default='DEBUTANT', max_length=20, verbose_name="Niveau d'expérience requis"),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='recruteur',
            field=models.ForeignKey(blank=True, help_text='Recruteur associé (pour les offres créées manuellement)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_emploi', to='myAppli.recruteur', verbose_name='Recruteur'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Salaire maximum (FCFA)'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Salaire minimum (FCFA)'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('PUBLIEE', 'Publiée'), ('POURVOIE', 'Pourvue'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('TEMPORAIRE', 'Temporaire'), ('CONSULTANCE', 'Consultance'), ('VOLONTARIAT', 'Volontariat')], default='CDI', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterUniqueTogether(
            name='offreemploi',
            unique_together={('source', 'source_id')},
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['source'], name='myAppli_off_source_83cd28_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['secteur'], name='myAppli_off_secteur_8eaca2_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['type_contrat'], name='myAppli_off_type_co_ffec9e_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['ville', 'pays'], name='myAppli_off_ville_f2e7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['hash_contenu'], name='myAppli_off_hash_co_fba3ed_idx'),
        ),
        migrations.AddField(
            model_name='logscraping',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppli.sourcescraping'),
        ),
    ]
