# Generated by Django 6.0.2 on 2026-05-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0011_dossiercandidature_points_faibles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('type_entretien', models.CharField(choices=[('presentiel', 'Entretien présentiel'), ('visio', 'Entretien en ligne (visio)'), ('telephone', 'Entretien téléphonique'), ('technique', 'Test technique')], max_length=20)),
                ('lieu_rdv', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('confirmee', 'Confirmée par le candidat'), ('annulee', 'Annulée')], default='envoyee', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='myAppli.dossiercandidature')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppli.recruteur')),
            ],
        ),
    ]
