# Generated by Django 6.0.2 on 2026-05-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0012_convocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addendum_uemoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('download_url', models.URLField(max_length=500)),
                ('fichier_local', models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='pdfs/')),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('traite_par_ia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dp_uemoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('download_url', models.URLField(max_length=500)),
                ('fichier_local', models.FileField(blank=True, help_text='Fichier PDF stocké en local', null=True, upload_to='pdfs/')),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('traite_par_ia', models.BooleanField(default=False)),
            ],
        ),
    ]
