# Generated by Django 6.0.2 on 2026-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0012_logscraping_sourcescraping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvgenere',
            name='derniere_utilisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvgenere',
            name='est_favori',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cvgenere',
            name='est_utilise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cvgenere',
            name='nb_telechargements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvgenere',
            name='nb_utilisations',
            field=models.IntegerField(default=0),
        ),
    ]
