# Generated by Django 6.0.2 on 2026-05-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0013_addendum_uemoa_dp_uemoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum_uemoa',
            name='autorite_contractante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='montant_dossier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='autorite_contractante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='montant_dossier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='autorite_contractante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='montant_dossier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='autorite_contractante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='montant_dossier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
