# Generated by Django 6.0.2 on 2026-05-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppli', '0014_addendum_uemoa_autorite_contractante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum_uemoa',
            name='delai_execution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='garantie_soumission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='lieu_depot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='montant_previsionnel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addendum_uemoa',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='delai_execution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='garantie_soumission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='lieu_depot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='montant_previsionnel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ami_uemoa',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='delai_execution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='garantie_soumission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='lieu_depot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='montant_previsionnel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dp_uemoa',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='delai_execution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='garantie_soumission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='lieu_depot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='montant_previsionnel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offre_uemoa',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
