# Generated by Django 6.0.2 on 2026-03-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myAppli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('texte_extrait', models.TextField(blank=True)),
                ('mots_cles', models.JSONField(default=dict, help_text='Mots-clés avec leur poids')),
                ('entites', models.JSONField(default=dict, help_text='Entités nommées extraites')),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('temps_analyse_ms', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(max_length=500, upload_to='pdfs/')),
                ('nom_fichier', models.CharField(max_length=255, unique=True)),
                ('taille', models.IntegerField(default=0, help_text='Taille en octets')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('url_source', models.URLField(blank=True, max_length=500)),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('ami_scrapee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_pdf', to='myAppli.ami_uemoa')),
                ('offre_scrapee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_pdf', to='myAppli.offre_uemoa')),
            ],
        ),
        migrations.CreateModel(
            name='ElementsExtraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('autorite', models.CharField(blank=True, max_length=300)),
                ('emails', models.JSONField(default=list)),
                ('telephones', models.JSONField(default=list)),
                ('date_extraction', models.DateTimeField(auto_now_add=True)),
                ('version_extraction', models.CharField(default='1.0', max_length=20)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='analyse_ia.analysedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunite_type', models.CharField(max_length=50)),
                ('opportunite_id', models.PositiveIntegerField()),
                ('score_competences', models.FloatField(default=0.0)),
                ('score_geographique', models.FloatField(default=0.0)),
                ('score_financier', models.FloatField(default=0.0)),
                ('score_global', models.FloatField(default=0.0)),
                ('competences_match', models.JSONField(default=list)),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
                ('cliquee', models.BooleanField(default=False)),
                ('candidatee', models.BooleanField(default=False)),
                ('analyse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyse_ia.analysedocument')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='myAppli.entreprise')),
            ],
            options={
                'ordering': ['-score_global'],
            },
        ),
        migrations.AddIndex(
            model_name='analysedocument',
            index=models.Index(fields=['content_type', 'object_id'], name='analyse_ia__content_461c0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analysedocument',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='documentsource',
            index=models.Index(fields=['nom_fichier'], name='analyse_ia__nom_fic_ee4622_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsource',
            index=models.Index(fields=['offre_scrapee'], name='analyse_ia__offre_s_48a193_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsource',
            index=models.Index(fields=['ami_scrapee'], name='analyse_ia__ami_scr_da0c11_idx'),
        ),
        migrations.AddIndex(
            model_name='elementsextraits',
            index=models.Index(fields=['date_limite'], name='analyse_ia__date_li_1f1dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='elementsextraits',
            index=models.Index(fields=['lieu'], name='analyse_ia__lieu_3ed904_idx'),
        ),
        migrations.AddIndex(
            model_name='recommandation',
            index=models.Index(fields=['entreprise', 'score_global'], name='analyse_ia__entrepr_da968e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommandation',
            index=models.Index(fields=['date_recommandation'], name='analyse_ia__date_re_736163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommandation',
            unique_together={('entreprise', 'opportunite_type', 'opportunite_id')},
        ),
    ]
