# Generated by Django 6.0.2 on 2026-02-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('texte_extrait', models.TextField(blank=True)),
                ('mots_cles', models.JSONField(default=dict, help_text='Mots-clés avec leur poids')),
                ('entites', models.JSONField(default=dict, help_text='Entités nommées extraites')),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('temps_analyse_ms', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='analyse_ia__content_461c0c_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
