# Generated by Django 6.0.2 on 2026-02-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0001_initial'),
        ('myAppli', '0003_ami_uemoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(max_length=500, upload_to='pdfs/')),
                ('nom_fichier', models.CharField(max_length=255, unique=True)),
                ('taille', models.IntegerField(default=0, help_text='Taille en octets')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('url_source', models.URLField(blank=True, max_length=500)),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('ami_scrapee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_pdf', to='myAppli.ami_uemoa')),
                ('offre_scrapee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_pdf', to='myAppli.offre_uemoa')),
            ],
            options={
                'indexes': [models.Index(fields=['nom_fichier'], name='analyse_ia__nom_fic_ee4622_idx'), models.Index(fields=['offre_scrapee'], name='analyse_ia__offre_s_48a193_idx'), models.Index(fields=['ami_scrapee'], name='analyse_ia__ami_scr_da0c11_idx')],
            },
        ),
    ]
