# Generated by Django 6.0.2 on 2026-04-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0001_initial'),
        ('myAppli', '0007_offreemploi_fichier_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommandationEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_competences', models.FloatField(default=0.0)),
                ('score_experience', models.FloatField(default=0.0)),
                ('score_formation', models.FloatField(default=0.0)),
                ('score_secteur', models.FloatField(default=0.0)),
                ('score_localisation', models.FloatField(default=0.0)),
                ('score_global', models.FloatField(default=0.0)),
                ('competences_match', models.JSONField(default=list)),
                ('competences_manquantes', models.JSONField(default=list)),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
                ('cliquee', models.BooleanField(default=False)),
                ('postule', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations_emploi', to='myAppli.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='myAppli.offreemploi')),
            ],
            options={
                'ordering': ['-score_global'],
                'indexes': [models.Index(fields=['candidat', 'score_global'], name='analyse_ia__candida_d04d8c_idx'), models.Index(fields=['date_recommandation'], name='analyse_ia__date_re_0a9388_idx')],
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
