# Generated by Django 6.0.2 on 2026-04-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0002_recommandationemploi'),
        ('myAppli', '0007_offreemploi_fichier_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementsCVExtraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competences', models.JSONField(default=list, help_text='Liste des compétences détectées')),
                ('niveau_etude', models.CharField(blank=True, help_text='Bac, Licence, Master, Doctorat...', max_length=100)),
                ('domaine_etude', models.CharField(blank=True, help_text='Informatique, Finance, Marketing...', max_length=100)),
                ('annees_experience', models.IntegerField(default=0, help_text="Nombre d'années d'expérience détecté")),
                ('postes_occupes', models.JSONField(default=list, help_text='Liste des postes occupés')),
                ('langues', models.JSONField(default=list, help_text='Langues détectées')),
                ('secteurs', models.JSONField(default=list, help_text="Secteurs d'activité détectés")),
                ('emails', models.JSONField(default=list)),
                ('telephones', models.JSONField(default=list)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('date_extraction', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elements_cv', to='analyse_ia.analysedocument')),
                ('candidat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_cv', to='myAppli.candidat')),
            ],
            options={
                'verbose_name': 'Éléments CV extraits',
                'verbose_name_plural': 'Éléments CV extraits',
                'indexes': [models.Index(fields=['niveau_etude'], name='analyse_ia__niveau__527fb2_idx'), models.Index(fields=['annees_experience'], name='analyse_ia__annees__4184d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElementsOffreExtraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competences_detectees', models.JSONField(default=list, help_text='Compétences détectées dans le texte/PDF')),
                ('niveau_etude_detecte', models.CharField(blank=True, help_text='Niveau détecté dans le texte', max_length=100)),
                ('domaine_etude_detecte', models.CharField(blank=True, max_length=100)),
                ('annees_experience_detectees', models.IntegerField(default=0, help_text="Années d'expérience détectées dans le texte")),
                ('langues_detectees', models.JSONField(default=list)),
                ('secteurs_detectes', models.JSONField(default=list)),
                ('emails', models.JSONField(default=list)),
                ('telephones', models.JSONField(default=list)),
                ('ville_detectee', models.CharField(blank=True, max_length=100)),
                ('pays_detecte', models.CharField(blank=True, max_length=100)),
                ('salaire_detecte', models.CharField(blank=True, max_length=100)),
                ('date_extraction', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elements_offre', to='analyse_ia.analysedocument')),
                ('offre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_extraits', to='myAppli.offreemploi')),
            ],
            options={
                'verbose_name': 'Éléments Offre extraits',
                'verbose_name_plural': 'Éléments Offres extraits',
                'indexes': [models.Index(fields=['niveau_etude_detecte'], name='analyse_ia__niveau__d0c12c_idx'), models.Index(fields=['annees_experience_detectees'], name='analyse_ia__annees__5b64a2_idx')],
            },
        ),
    ]
