# Generated by Django 6.0.2 on 2026-02-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0002_documentsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementsExtraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('autorite', models.CharField(blank=True, max_length=300)),
                ('emails', models.JSONField(default=list)),
                ('telephones', models.JSONField(default=list)),
                ('date_extraction', models.DateTimeField(auto_now_add=True)),
                ('version_extraction', models.CharField(default='1.0', max_length=20)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='analyse_ia.analysedocument')),
            ],
            options={
                'indexes': [models.Index(fields=['date_limite'], name='analyse_ia__date_li_1f1dc0_idx'), models.Index(fields=['lieu'], name='analyse_ia__lieu_3ed904_idx')],
            },
        ),
    ]
