# Generated by Django 6.0.2 on 2026-02-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0003_elementsextraits'),
        ('myAppli', '0004_alter_entreprise_options_remove_entreprise_attribut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunite_type', models.CharField(max_length=50)),
                ('opportunite_id', models.PositiveIntegerField()),
                ('score_competences', models.FloatField(default=0.0)),
                ('score_geographique', models.FloatField(default=0.0)),
                ('score_financier', models.FloatField(default=0.0)),
                ('score_global', models.FloatField(default=0.0)),
                ('competences_match', models.JSONField(default=list)),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
                ('cliquee', models.BooleanField(default=False)),
                ('candidatee', models.BooleanField(default=False)),
                ('analyse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyse_ia.analysedocument')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='myAppli.entreprise')),
            ],
            options={
                'ordering': ['-score_global'],
                'indexes': [models.Index(fields=['entreprise', 'score_global'], name='analyse_ia__entrepr_ee1ca8_idx'), models.Index(fields=['date_recommandation'], name='analyse_ia__date_re_dbffde_idx')],
                'unique_together': {('entreprise', 'opportunite_type', 'opportunite_id')},
            },
        ),
    ]
