# Generated by Django 6.0.2 on 2026-04-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0003_elementscvextraits_elementsoffreextraits'),
        ('myAppli', '0007_offreemploi_fichier_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_vise', models.CharField(blank=True, help_text='Poste visé (rempli auto depuis offre ou saisi manuellement)', max_length=200)),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ABANDONNEE', 'Abandonnée')], default='EN_COURS', max_length=20)),
                ('score_global', models.FloatField(default=0.0, help_text='Score moyen sur 10')),
                ('feedback_global', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(default=0)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_entretien', to='myAppli.candidat')),
                ('offre', models.ForeignKey(blank=True, help_text='Null = cas général', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_entretien', to='myAppli.offreemploi')),
            ],
            options={
                'verbose_name': "Session d'entretien",
                'verbose_name_plural': "Sessions d'entretien",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='QuestionEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(help_text='Position dans la session (1-10)')),
                ('type_question', models.CharField(choices=[('TECHNIQUE', 'Technique'), ('COMPORTEMENTALE', 'Comportementale'), ('SITUATIONNELLE', 'Situationnelle'), ('MOTIVATION', 'Motivation')], default='COMPORTEMENTALE', max_length=20)),
                ('question', models.TextField()),
                ('reponse_candidat', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('feedback_ia', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0, help_text='Score sur 10')),
                ('points_forts', models.JSONField(default=list)),
                ('points_amelioration', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analyse_ia.sessionentretien')),
            ],
            options={
                'verbose_name': "Question d'entretien",
                'ordering': ['ordre'],
                'unique_together': {('session', 'ordre')},
            },
        ),
    ]
