# Generated by Django 6.0.2 on 2026-05-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0004_sessionentretien_questionentretien'),
        ('myAppli', '0010_lettremotivationgeneree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommandationCandidatRecruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.FloatField(default=0.0)),
                ('score_competences', models.FloatField(default=0.0)),
                ('score_experience', models.FloatField(default=0.0)),
                ('score_formation', models.FloatField(default=0.0)),
                ('explication', models.TextField(blank=True, help_text='Explication Ollama de la compatibilité')),
                ('points_forts', models.JSONField(default=list)),
                ('points_faibles', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('INVITE', 'Invité'), ('ACCEPTE', 'A postulé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('date_invitation', models.DateTimeField(blank=True, null=True)),
                ('vue', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations_recruteur', to='myAppli.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats_recommandes', to='myAppli.offreemploi')),
            ],
            options={
                'verbose_name': 'Candidat recommandé',
                'verbose_name_plural': 'Candidats recommandés',
                'ordering': ['-score_global'],
                'unique_together': {('offre', 'candidat')},
            },
        ),
    ]
