# Generated by Django 6.0.2 on 2026-02-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0004_recommendation'),
    ]

    operations = [
    ]
