# Generated by Django 6.0.2 on 2026-02-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0006_renommer_recommandation'),
        ('myAppli', '0004_alter_entreprise_options_remove_entreprise_attribut_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Recommandation',
        ),
        migrations.RenameIndex(
            model_name='recommandation',
            new_name='analyse_ia__entrepr_da968e_idx',
            old_name='analyse_ia__entrepr_ee1ca8_idx',
        ),
        migrations.RenameIndex(
            model_name='recommandation',
            new_name='analyse_ia__date_re_736163_idx',
            old_name='analyse_ia__date_re_dbffde_idx',
        ),
    ]
